# Generated by Django 5.2.5 on 2025-09-05 11:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Nishon nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Nishon ikonasi')),
                ('trigger_condition', models.CharField(max_length=100, verbose_name='Trigger sharti')),
                ('condition_params', models.JSONField(blank=True, help_text="JSON formatida qo'shimcha shartlar (masalan, {'min_score': 80, 'exam_count': 5})", null=True, verbose_name='Shart parametrlari')),
            ],
            options={
                'verbose_name': 'Nishon (Yutuq)',
                'verbose_name_plural': 'Nishonlar (Yutuqlar)',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('adaptive', 'Adaptiv (generatsiyalanuvchi)'), ('static', 'Statik (qotirilgan)')], default='adaptive', help_text="Adaptiv - qoidalar asosida, Statik - aniq savollar ro'yxati asosida", max_length=20, verbose_name='Imtihon turi')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Pullik imtihon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
            },
        ),
        migrations.CreateModel(
            name='ExamPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('exam_credits', models.PositiveIntegerField(verbose_name='Beriladigan imtihonlar soni (kredit)')),
                ('solution_view_credits_on_purchase', models.PositiveIntegerField(default=0, verbose_name='Beriladigan yechimlar soni (kredit)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Imtihon paketi',
                'verbose_name_plural': 'Imtihon paketlari',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Matn sarlavhasi')),
                ('content', models.TextField(verbose_name='Matn (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matn (Passage)',
                'verbose_name_plural': 'Matnlar (Passages)',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo kod')),
                ('discount_type', models.CharField(choices=[('percentage', 'Foiz'), ('fixed', 'Fiks summa')], default='percentage', max_length=20, verbose_name='Chegirma turi')),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Foiz chegirmasi uchun, masalan, 10% uchun 10 kiriting', null=True, verbose_name='Chegirma foizi')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Fiks summa chegirmasi uchun, masalan, 50000 so'm", max_digits=10, null=True, verbose_name='Fiks chegirma summasi')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Amal qilish boshlanishi')),
                ('valid_until', models.DateTimeField(verbose_name='Amal qilish tugashi')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Maksimal ishlatishlar soni')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ishlatilganlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
            },
        ),
        migrations.CreateModel(
            name='RaschDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Daraja nomi')),
                ('min_difficulty', models.FloatField(default=-3.0, verbose_name='Minimal qiyinlik')),
                ('max_difficulty', models.FloatField(default=3.0, verbose_name='Maksimal qiyinlik')),
            ],
            options={
                'verbose_name': 'Rasch qiyinlik darajasi',
                'verbose_name_plural': 'Rasch qiyinlik darajalari',
                'ordering': ['min_difficulty'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Obuna rejasi nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('duration_days', models.PositiveIntegerField(verbose_name='Amal qilish muddati (kunda)')),
                ('includes_solution_access', models.BooleanField(default=False, verbose_name="Yechimlarni ko'rishni o'z ichiga oladimi?")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ichki mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Ichki mavzu',
                'verbose_name_plural': 'Ichki mavzular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_calibration_threshold', models.PositiveIntegerField(default=30, help_text="Savolning qiyinlik darajasi shu sondagi javoblardan so'ng avtomatik hisoblanadi.", verbose_name='Savolni kalibrovka qilish uchun minimal javoblar soni')),
                ('solutions_enabled', models.BooleanField(default=True, verbose_name='Savol yechimlarini yoqish')),
                ('default_solutions_are_free', models.BooleanField(default=False, help_text="Agar bu yoqilgan bo'lsa, 'Yechim bepulmi?' deb belgilanmagan barcha savollar yechimi pullik bo'ladi.", verbose_name='Standart holatda yechimlar bepulmi?')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Teg nomi')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Umumiy mavzu',
                'verbose_name_plural': 'Umumiy mavzular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing and Language'), ('math_no_calc', 'Math (No Calculator)'), ('math_calc', 'Math (Calculator)')], max_length=30, verbose_name='Bo‘lim turi')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Davomiyligi (minut)')),
                ('max_questions', models.PositiveIntegerField(verbose_name='Maksimal savollar soni')),
                ('module_number', models.PositiveIntegerField(default=1, verbose_name='Modul raqami')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('min_difficulty', models.FloatField(blank=True, null=True, verbose_name='Minimal qiyinlik (Rasch)')),
                ('max_difficulty', models.FloatField(blank=True, null=True, verbose_name='Maksimal qiyinlik (Rasch)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Mock.exam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': 'Imtihon bo‘limi',
                'verbose_name_plural': 'Imtihon bo‘limlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSectionTopicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_rules', to='Mock.examsection', verbose_name='Bo‘lim')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.topic', verbose_name='Umumiy mavzu')),
            ],
            options={
                'verbose_name': 'Bo‘lim mavzu qoidasi (Adaptiv)',
                'verbose_name_plural': 'Bo‘lim mavzu qoidalari (Adaptiv)',
                'unique_together': {('exam_section', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='FlashcardExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Flashcard mashg'ulot nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_exam', to='Mock.exam', verbose_name='Asosiy imtihon')),
            ],
            options={
                'verbose_name': "Flashcard mashg'uloti",
                'verbose_name_plural': "Flashcard mashg'ulotlari",
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Savol rasmi')),
                ('answer_format', models.CharField(choices=[('single', 'Yagona tanlov'), ('multiple', "Ko'p tanlov"), ('short_answer', 'Qisqa javob')], default='single', max_length=20, verbose_name='Javob formati')),
                ('difficulty', models.FloatField(db_index=True, default=0.0, verbose_name='Qiyinlik darajasi (Rasch)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('is_calibrated', models.BooleanField(db_index=True, default=False, verbose_name='Kalibrlanganmi?')),
                ('response_count', models.PositiveIntegerField(default=0, verbose_name='Javoblar soni')),
                ('is_solution_free', models.BooleanField(default=False, verbose_name='Yechim bepulmi?')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='Mock.question', verbose_name='Asl (ota-ona) savol')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Mock.passage', verbose_name='Matn')),
                ('difficulty_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.raschdifficultylevel', verbose_name='Qiyinlik darajasi')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='Mock.subtopic', verbose_name='Ichki mavzu')),
                ('tags', models.ManyToManyField(blank=True, to='Mock.tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('word', "So'z/Ibora"), ('formula', 'Formula'), ('image', 'Rasm')], default='word', max_length=20, verbose_name='Kontent turi')),
                ('english_content', models.CharField(db_index=True, max_length=255, verbose_name='Inglizcha kontent')),
                ('uzbek_meaning', models.CharField(max_length=255, verbose_name="O'zbekcha ma'nosi")),
                ('context_sentence', models.TextField(blank=True, null=True, verbose_name='Kontekst (gap)')),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='flashcards/', verbose_name='Rasm kontenti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='Mock.question', verbose_name='Manba-savol')),
            ],
            options={
                'verbose_name': "Flashcard (lug'at)",
                'verbose_name_plural': "Flashcardlar (lug'atlar)",
                'unique_together': {('english_content', 'source_question')},
            },
        ),
        migrations.CreateModel(
            name='ExamSectionStaticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Savol tartib raqami')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.examsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
            ],
            options={
                'verbose_name': "Bo'limning statik savoli",
                'verbose_name_plural': "Bo'limning statik savollari",
                'ordering': ['question_number'],
                'unique_together': {('exam_section', 'question')},
            },
        ),
        migrations.AddField(
            model_name='examsection',
            name='static_questions',
            field=models.ManyToManyField(blank=True, related_name='static_exam_sections', through='Mock.ExamSectionStaticQuestion', to='Mock.question', verbose_name='Statik savollar'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Mock.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_solution', models.TextField(blank=True, null=True, verbose_name='Qisqa yechim (AI)')),
                ('detailed_solution', models.TextField(blank=True, null=True, verbose_name='Batafsil yechim (AI)')),
                ('solution_generation_status', models.CharField(choices=[('not_generated', 'Yaratilmagan'), ('pending', 'Kutilmoqda'), ('completed', 'Yaratilgan'), ('failed', 'Xatolik')], default='not_generated', max_length=20, verbose_name='Yechim generatsiya holati')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='Mock.question')),
            ],
            options={
                'verbose_name': 'Savol yechimi',
                'verbose_name_plural': 'Savol yechimlari',
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='Mock.topic', verbose_name='Umumiy mavzu'),
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Tugatilgan')),
                ('final_ebrw_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy EBRW balli')),
                ('final_math_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy Math balli')),
                ('final_total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy umumiy ball')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.exam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi urinishi',
                'verbose_name_plural': 'Foydalanuvchi urinishlari',
            },
        ),
        migrations.CreateModel(
            name='UserAttemptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Bo‘lim balli')),
                ('ability_estimate', models.FloatField(default=0.0, verbose_name='Taxminiy qobiliyat (Rasch)')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_answers_count', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('remaining_time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qolgan vaqt (soniya)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='Mock.userattempt', verbose_name='Urinish')),
                ('questions', models.ManyToManyField(blank=True, related_name='attempted_in_sections', to='Mock.question', verbose_name='Berilgan savollar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.examsection', verbose_name='Bo‘lim')),
            ],
            options={
                'verbose_name': 'Bo‘lim urinishi',
                'verbose_name_plural': 'Bo‘lim urinishlari',
                'unique_together': {('attempt', 'section')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa javob matni')),
                ('is_correct', models.BooleanField(null=True, verbose_name="To'g'riligi")),
                ('answered_at', models.DateTimeField()),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (soniya)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='Mock.answeroption', verbose_name='Tanlangan variantlar')),
                ('attempt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_answers', to='Mock.userattemptsection')),
            ],
            options={
                'verbose_name': 'Arxivlangan foydalanuvchi javobi',
                'verbose_name_plural': 'Arxivlangan foydalanuvchi javoblari',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Ustoz'), ('student', 'Talaba'), ('admin', 'Administrator')], default='student', max_length=20, verbose_name='Foydalanuvchi roli')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('ability', models.FloatField(default=0.0, verbose_name='Foydalanuvchi qobiliyati (Rasch)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name="O'zi haqida")),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan ustoz')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Boshlangan sana')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sana')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.subscriptionplan', verbose_name='Obuna rejasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="To'plam nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcards', models.ManyToManyField(blank=True, to='Mock.flashcard', verbose_name="To'plamdagi kartochkalar")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Shaxsiy flashcard to'plami",
                'verbose_name_plural': "Shaxsiy flashcard to'plamlari",
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_credits', models.PositiveIntegerField(default=0, verbose_name='Mavjud imtihon kreditlari')),
                ('solution_view_credits', models.PositiveIntegerField(default=0, verbose_name='Mavjud yechim kreditlari')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi balansi',
                'verbose_name_plural': 'Foydalanuvchi balanslari',
            },
        ),
        migrations.AddField(
            model_name='userattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ustoz'),
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi')], db_index=True, default='open', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Mock.question', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xabar bergan foydalanuvchi')),
            ],
            options={
                'verbose_name': "Savol bo'yicha shikoyat",
                'verbose_name_plural': "Savollar bo'yicha shikoyatlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('package', 'Paket'), ('subscription', 'Obuna')], max_length=20, verbose_name='Xarid turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Boshlang'ich summa")),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Xatolik')], db_index=True, default='pending', max_length=20, verbose_name='Holati')),
                ('payment_gateway_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="To'lov tizimi IDsi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.exampackage', verbose_name='Paket')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.promocode', verbose_name='Promo kod')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.subscriptionplan', verbose_name='Obuna rejasi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xarid',
                'verbose_name_plural': 'Xaridlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilganmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='Mock.flashcardexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Flashcard mashg'uloti urinishi",
                'verbose_name_plural': "Flashcard mashg'uloti urinishlari",
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ustoz'),
        ),
        migrations.CreateModel(
            name='AnswerOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('text', models.TextField(verbose_name='Variant matni (HTML)')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Mock.answeroption')),
            ],
            options={
                'verbose_name': 'Javob varianti tarjimasi',
                'verbose_name_plural': 'Javob variantlari tarjimasi',
                'unique_together': {('answer_option', 'language')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examsection',
            unique_together={('exam', 'section_type', 'module_number')},
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('text', models.TextField(verbose_name='Savol matni (HTML)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Mock.question')),
            ],
            options={
                'verbose_name': 'Savol tarjimasi',
                'verbose_name_plural': 'Savol tarjimasi',
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExamSectionSubtopicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('topic_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_rules', to='Mock.examsectiontopicrule', verbose_name='Mavzu qoidasi')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.subtopic', verbose_name='Ichki mavzu')),
            ],
            options={
                'verbose_name': 'Bo‘lim ichki mavzu qoidasi (Adaptiv)',
                'verbose_name_plural': 'Bo‘lim ichki mavzu qoidalari (Adaptiv)',
                'unique_together': {('topic_rule', 'subtopic')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('name', 'topic')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa javob matni')),
                ('is_correct', models.BooleanField(null=True, verbose_name="To'g'riligi")),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (soniya)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='Mock.answeroption', verbose_name='Tanlangan variantlar')),
                ('attempt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='Mock.userattemptsection')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('attempt_section', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserSolutionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('credit_spent', models.BooleanField(default=False, verbose_name='Kredit sarflandimi?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to='Mock.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ko'rilgan savol yechimi",
                'verbose_name_plural': "Ko'rilgan savol yechimlari",
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_learned', "O'rganilmagan"), ('learning', "O'rganilmoqda"), ('learned', "O'rganilgan")], db_index=True, default='not_learned', max_length=20, verbose_name="O'zlashtirish holati")),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi ko'rilgan vaqt")),
                ('next_review_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Keyingi takrorlash vaqti')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Osonlik faktori')),
                ('review_interval', models.PositiveIntegerField(default=1, verbose_name='Takrorlash intervali (kunda)')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='Mock.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi flashcard holati',
                'verbose_name_plural': 'Foydalanuvchi flashcard holatlari',
                'unique_together': {('user', 'flashcard')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='Mock.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi nishoni',
                'verbose_name_plural': 'Foydalanuvchi nishonlari',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'teacher')},
        ),
    ]
