# Generated by Django 4.2.1 on 2025-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['english_content'], 'verbose_name': "Flashcard (lug'at)", 'verbose_name_plural': "Flashcardlar (lug'atlar)"},
        ),
    ]
