# Generated by Django 5.2.5 on 2025-09-17 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsectionsubtopicrule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='badge',
            name='condition_params',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='trigger_condition',
        ),
        migrations.AddField(
            model_name='badge',
            name='exam_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Imtihon yakunlandi' tanlangan bo'lsa, shu son yetkazilsa nishon beriladi", verbose_name='Imtihonlar soni (imtihon yakunlash meyorida)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='flashcard_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Flashcard o'rganildi' tanlangan bo'lsa, shu son o'rganilsa nishon beriladi", verbose_name="Flashcardlar soni (flashcard o'rganish meyorida)"),
        ),
        migrations.AddField(
            model_name='badge',
            name='min_score',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Ball yetkazildi' tanlangan bo'lsa, shu balldan yuqori bo'lsa nishon beriladi", verbose_name='Minimal ball (ball yetkazish meyorida)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='streak_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Ketma-ketlik' tanlangan bo'lsa, shu kun ketma-ket mashq qilinsa nishon beriladi", verbose_name='Ketma-ket kunlar soni (ketma-ketlik meyorida)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='trigger_type',
            field=models.CharField(choices=[('exam_completed', 'Imtihon yakunlandi'), ('score_achieved', 'Ball yetkazildi'), ('streak', 'Ketma-ketlik'), ('flashcard_learned', "Flashcard o'rganildi")], default=1, help_text='Nishon qachon berilishini tanlang', max_length=50, verbose_name='Meyor turi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='discrimination',
            field=models.FloatField(default=1.0, verbose_name='Farqlash parametri (IRT discrimination)'),
        ),
        migrations.AddField(
            model_name='question',
            name='guessing',
            field=models.FloatField(default=0.25, verbose_name='Taxmin parametri (IRT guessing)'),
        ),
        migrations.AddField(
            model_name='userattemptsection',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Yakunlangan'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='max_difficulty',
            field=models.FloatField(blank=True, null=True, verbose_name='Maksimal qiyinlik (IRT)'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='min_difficulty',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimal qiyinlik (IRT)'),
        ),
        migrations.AlterField(
            model_name='examsectionsubtopicrule',
            name='questions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Savollar soni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Qiyinlik darajasi (IRT difficulty)'),
        ),
        migrations.AlterField(
            model_name='userattemptsection',
            name='ability_estimate',
            field=models.FloatField(default=0.0, verbose_name='Taxminiy qobiliyat (IRT)'),
        ),
        migrations.CreateModel(
            name='LiveExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Imtihon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('registration_deadline', models.DateTimeField(verbose_name="Ro'yxatdan o'tish oxirgi muddati")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narx (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_exams', to='Mock.exam', verbose_name="Bog'langan imtihon")),
            ],
            options={
                'verbose_name': 'Live Imtihon',
                'verbose_name_plural': 'Live Imtihonlar',
            },
        ),
        migrations.CreateModel(
            name='LiveExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', "To'langan"), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name="To'lov holati")),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'langan summa")),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('live_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Mock.liveexam', verbose_name='Live Imtihon')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_exam_registration', to='Mock.purchase', verbose_name="Bog'langan xarid")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_exam_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Live Imtihon Ro'yxati",
                'verbose_name_plural': "Live Imtihon Ro'yxatlari",
                'unique_together': {('live_exam', 'user')},
            },
        ),
    ]
