# Generated by Django 4.2.1 on 2025-11-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Mock", "0002_alter_flashcard_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattempt",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_attempts",
                to="Mock.exam",
                verbose_name="Imtihon",
            ),
        ),
    ]
