# Generated by Django 5.2.5 on 2025-09-24 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0002_alter_examsectionsubtopicrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='daily_min_score',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Kunlik minimal ball (eng yaxshi kunlik natija meyorida)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Taklif qilingan do'stlar soni (referral meyorida)"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='trigger_type',
            field=models.CharField(choices=[('exam_completed', 'Imtihon yakunlandi'), ('score_achieved', 'Ball yetkazildi'), ('streak', 'Ketma-ketlik'), ('flashcard_learned', "Flashcard o'rganildi"), ('daily_high_score', 'Eng yaxshi kunlik natija'), ('referral', "Do'stlarni taklif qilish")], help_text='Nishon qachon berilishini tanlang', max_length=50, verbose_name='Meyor turi'),
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attempts_completed', models.PositiveIntegerField(default=0, verbose_name='Yakunlangan exam mode urinishlari')),
                ('study_attempts_completed', models.PositiveIntegerField(default=0, verbose_name='Yakunlangan study mode urinishlari')),
                ('highest_score', models.PositiveIntegerField(default=0, verbose_name='Eng yuqori ball (exam mode)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi missiya progressi',
                'verbose_name_plural': 'Foydalanuvchi missiya progresslari',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('effort', "Mehnat bo'yicha (ko'p imtihon ishlaganlar)"), ('performance', "Natija bo'yicha (yuqori ball olganlar)")], max_length=20, verbose_name='Leaderboard turi')),
                ('week_number', models.PositiveIntegerField(verbose_name='Hafta raqami')),
                ('score', models.PositiveIntegerField(default=0, verbose_name="Ball yoki ko'rsatkich")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard kirishi',
                'verbose_name_plural': 'Leaderboard kirishlari',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['leaderboard_type', 'week_number', '-score'], name='Mock_leader_leaderb_4747ef_idx')],
                'unique_together': {('user', 'leaderboard_type', 'week_number')},
            },
        ),
    ]
