# Generated by Django 5.2.6 on 2025-09-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0002_flashcard_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='image_content',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='content_type',
            field=models.CharField(choices=[('word', "So'z/Ibora"), ('formula', 'Formula')], default='word', max_length=20, verbose_name='Kontent turi'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='english_content',
            field=models.TextField(verbose_name='Inglizcha kontent'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_flashcards', to='Mock.question', verbose_name='Manba-savol'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='uzbek_meaning',
            field=models.TextField(verbose_name="O'zbekcha ma'nosi"),
        ),
    ]
