# Generated by Django 5.2.5 on 2025-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0003_remove_flashcard_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flashcards',
            field=models.ManyToManyField(blank=True, related_name='questions', to='Mock.flashcard', verbose_name='Savolga oid flashcardlar'),
        ),
    ]
