# Generated by Django 5.2.5 on 2025-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0003_badge_daily_min_score_badge_referral_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='mode',
            field=models.CharField(default='exam', max_length=50, verbose_name='Imtihon rejimi'),
        ),
    ]
