# Generated by Django 5.2.5 on 2025-09-11 04:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0004_question_flashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='text',
            field=tinymce.models.HTMLField(default='<p></p>', verbose_name='Variant matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(default='<p></p>', verbose_name='Savol matni'),
        ),
    ]
