# Generated by Django 4.2.1 on 2025-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mock", "0004_alter_examsectionorder_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="Mock.group",
                verbose_name="Kurs o'tiladigan guruhlar",
            ),
        ),
    ]
