# Generated by Django 5.2.5 on 2025-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0004_userattempt_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_marked_for_review',
            field=models.BooleanField(default=False, verbose_name="Ko'rib chiqish uchun belgilangan"),
        ),
    ]
