# Generated by Django 5.2.5 on 2025-09-11 05:58

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0005_answeroption_text_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsolution',
            options={'verbose_name': 'Savol yechimi', 'verbose_name_plural': 'Savollar yechimi'},
        ),
        migrations.RemoveField(
            model_name='questionsolution',
            name='short_solution',
        ),
        migrations.RemoveField(
            model_name='questionsolution',
            name='solution_generation_status',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_short_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="To'g'ri qisqa javob"),
        ),
        migrations.AddField(
            model_name='questionsolution',
            name='hint',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Yechim uchun maslahat'),
        ),
        migrations.AlterField(
            model_name='questionsolution',
            name='detailed_solution',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Yechim'),
        ),
        migrations.AlterField(
            model_name='questionsolution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='Mock.question', verbose_name='Savol'),
        ),
    ]
