# Generated by Django 5.2.5 on 2025-09-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0005_useranswer_is_marked_for_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userflashcardstatus',
            options={'verbose_name': 'Foydalanuvchi flashcard holati (SM2)', 'verbose_name_plural': 'Foydalanuvchi flashcard holatlari (SM2)'},
        ),
        migrations.AddField(
            model_name='userflashcardstatus',
            name='last_quality_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Oxirgi baho (0-5)'),
        ),
        migrations.AddField(
            model_name='userflashcardstatus',
            name='repetition_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli takrorlash soni'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='section_type',
            field=models.CharField(choices=[('read_write_m1', 'Reading'), ('read_write_m2', 'Writing and Language'), ('math_no_calc', 'Math (No Calculator)'), ('math_calc', 'Math (Calculator)')], max_length=30, verbose_name='Bo‘lim turi'),
        ),
        migrations.AlterField(
            model_name='userflashcardstatus',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Osonlik faktori (SM2)'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('english_content', 'author')},
        ),
        migrations.CreateModel(
            name='FlashcardReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.PositiveSmallIntegerField(verbose_name='Sifat bahosi (0-5)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'rib chiqish vaqti")),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_log', to='Mock.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard takrorlash logi',
                'verbose_name_plural': 'Flashcard takrorlash loglari',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.DeleteModel(
            name='FlashcardExamAttempt',
        ),
    ]
