# Generated by Django 5.2.5 on 2025-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0006_alter_questionsolution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampackage',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='packages', to='Mock.exam', verbose_name='Paketdagi imtihonlar'),
        ),
        migrations.AddField(
            model_name='flashcardexam',
            name='flashcards',
            field=models.ManyToManyField(blank=True, related_name='flashcard_exams', to='Mock.flashcard', verbose_name='Flashcardlar'),
        ),
    ]
