# Generated by Django 4.2.1 on 2025-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0006_alter_userflashcardstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='payment_gateway_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_comment',
            field=models.TextField(blank=True, null=True, verbose_name="To'lovga izoh"),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='screenshots/%Y/%m/', verbose_name="To'lov skrinshoti"),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('moderation', 'Tekshirilmoqda'), ('completed', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
