# Generated by Django 5.2.5 on 2025-09-15 12:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0007_exampackage_exams_flashcardexam_flashcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p></p>', verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='answeroptiontranslation',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Variant matni (HTML)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='context_sentence',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kontekst (gap)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='english_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inglizcha kontent'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='uzbek_meaning',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="O'zbekcha ma'nosi"),
        ),
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn (HTML)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p></p>', verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='questionsolution',
            name='detailed_solution',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yechim'),
        ),
        migrations.AlterField(
            model_name='questionsolution',
            name='hint',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yechim uchun maslahat'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol matni (HTML)'),
        ),
    ]
