# Generated by Django 4.2.1 on 2025-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0007_remove_purchase_payment_gateway_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_phone_number', models.CharField(help_text="To'lovni tezkor tasdiqlash uchun menejer telefon raqami. Format: +998901234567", max_length=20)),
                ('manager_telegram_username', models.CharField(blank=True, help_text="Menejerning telegram username'i (masalan, @menejer_username)", max_length=100)),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
