# Generated by Django 5.2.5 on 2025-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0008_alter_answeroption_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampackage',
            name='includes_flashcards',
            field=models.BooleanField(default=False, verbose_name="Flashcardlar to'plamini o'z ichiga oladimi?"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_flashcards',
            field=models.BooleanField(default=False, verbose_name="Flashcardlar to'plamini o'z ichiga oladimi?"),
        ),
    ]
