# Generated by Django 4.2.1 on 2025-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_holder',
            field=models.CharField(default=1, help_text='Karta egasining ismi va familiyasi. Masalan: ALI VALIYEV', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_number',
            field=models.CharField(default=1, help_text="To'lov qabul qilinadigan plastik karta raqami. Format: 8600 1234 ...", max_length=20),
            preserve_default=False,
        ),
    ]
