# Generated by Django 4.2.1 on 2025-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0009_sitesettings_payment_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='attempt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
