# Generated by Django 4.2.1 on 2025-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0010_userattempt_attempt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='userattempt',
            name='attempt_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
