# Generated by Django 4.2.1 on 2025-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0011_remove_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name="To'liq ism (F.I.Sh)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('teacher', 'Ustoz'), ('admin', 'Administrator')], default='student', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
